from __future__ import annotations

from pathlib import Path


IDE = "codex"


def default_target_paths(home: Path) -> list[Path]:
    return [home / ".codex" / "config.yaml"]


def plan_changes(skill_dir: Path) -> list[dict]:
    return [
        {
            "ide": IDE,
            "target_path": str(default_target_paths(Path.home())[0]),
            "description": "Configure MCP and vibe-marketing skill references for Codex.",
            "proposed_content": f"# generated by vm-onboard\nskill_path: {skill_dir}\n",
        }
    ]

