from __future__ import annotations

from pathlib import Path


IDE = "kimi"


def default_target_paths(home: Path) -> list[Path]:
    return [home / ".kimi" / "project-knowledge.md"]


def plan_changes(skill_dir: Path) -> list[dict]:
    return [
        {
            "ide": IDE,
            "target_path": str(default_target_paths(Path.home())[0]),
            "description": "Configure Kimi Project Knowledge link for vibe-marketing skill.",
            "proposed_content": (
                "# generated by vm-onboard\n"
                f"include_skill: {skill_dir / 'SKILL.md'}\n"
            ),
        }
    ]

